name: scrape

on:
  pull_request:
  push:

jobs:
  atuin: {uses: ./.github/workflows/scrape-template.yml, with: {command: atuin}}
  bazel: {uses: ./.github/workflows/scrape-template.yml, with: {command: bazel}}
  but: {uses: ./.github/workflows/scrape-template.yml, with: {command: but}}
  cargo: {uses: ./.github/workflows/scrape-template.yml, with: {command: cargo}}
  devbox: {uses: ./.github/workflows/scrape-template.yml, with: {command: devbox}}
  docker: {uses: ./.github/workflows/scrape-template.yml, with: {command: docker}}
  docker-compose: {uses: ./.github/workflows/scrape-template.yml, with: {command: docker-compose}}
  gh: {uses: ./.github/workflows/scrape-template.yml, with: {command: gh}}
  glab: {uses: ./.github/workflows/scrape-template.yml, with: {command: glab}}
  golangci-lint: {uses: ./.github/workflows/scrape-template.yml, with: {command: golangci-lint}}
  goreleaser: {uses: ./.github/workflows/scrape-template.yml, with: {command: goreleaser}}
  gum: {uses: ./.github/workflows/scrape-template.yml, with: {command: gum}}
  jj: {uses: ./.github/workflows/scrape-template.yml, with: {command: jj}}
  kubeadm: {uses: ./.github/workflows/scrape-template.yml, with: {command: kubeadm}}
  kubectl: {uses: ./.github/workflows/scrape-template.yml, with: {command: kubectl}}
  mdbook: {uses: ./.github/workflows/scrape-template.yml, with: {command: mdbook}}
  minikube: {uses: ./.github/workflows/scrape-template.yml, with: {command: minikube}}
  mise: {uses: ./.github/workflows/scrape-template.yml, with: {command: mise}}
  rustup: {uses: ./.github/workflows/scrape-template.yml, with: {command: rustup}}
  taplo: {uses: ./.github/workflows/scrape-template.yml, with: {command: taplo}}
  task: {uses: ./.github/workflows/scrape-template.yml, with: {command: task}}
  zoxide: {uses: ./.github/workflows/scrape-template.yml, with: {command: zoxide}}
